import { createServer } from '../src/index';
import fs from 'node:fs';
import path from 'node:path';

function assert(condition: boolean, message: string) {
  if (!condition) {
    throw new Error(`Assertion Failed: ${message}`);
  }
}

async function runAllTests() {
  console.log('🧪 Starting Reverse Logger Expanded Test Suite...\n');

  const testDbDir = path.join(process.cwd(), '.test-dbs');
  if (!fs.existsSync(testDbDir)) {
    fs.mkdirSync(testDbDir, { recursive: true });
  }

  // --- Test Suite 1: Core API & Response Schema ---
  {
    console.log('1. Testing Core API & Response Schema...');
    const dbPath = path.join(testDbDir, 'test1.db');
    if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);

    const port = 5101;
    const server = createServer({ port, maxLogs: 100, dbPath });
    await server.listen(port);

    const postRes = await fetch(`http://127.0.0.1:${port}/api/logs`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        level: 'info',
        message: 'System started',
        args: ['System started', { env: 'production' }],
        url: 'http://app.local/home',
        sessionId: 'sess_123',
      }),
    });
    assert(postRes.status === 200, 'POST /api/logs status should be 200');

    const getRes = await fetch(`http://127.0.0.1:${port}/api/logs`);
    assert(getRes.status === 200, 'GET /api/logs status should be 200');

    const data = await getRes.json();
    assert(Array.isArray(data.logs), 'data.logs should be an array');
    assert(typeof data.total === 'number', 'data.total should be a number');
    assert(data.limit === 20, 'data.limit should default to 20');
    assert(data.offset === 0, 'data.offset should default to 0');
    assert(data.logs.length === 1, 'data.logs should contain 1 record');
    assert(data.logs[0].sessionId === 'sess_123', 'sessionId should be preserved');
    assert(typeof data.logs[0].timestamp === 'string', 'timestamp should be ISO string');

    await server.close();
    console.log('   ✓ Core API & Schema OK');
  }

  // --- Test Suite 2: Starred Logs & Special Logs API ---
  {
    console.log('2. Testing Starred Logs & Special Logs API...');
    const dbPath = path.join(testDbDir, 'test2.db');
    if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);

    const port = 5102;
    const server = createServer({ port, maxLogs: 100, dbPath });
    await server.listen(port);

    // Ingest normal log
    await fetch(`http://127.0.0.1:${port}/api/logs`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        level: 'info',
        args: ['Normal console log'],
        source: 'console',
        starred: false,
      }),
    });

    // Ingest special starred log (as generated by window.reverseLogger.star)
    const specialRes = await fetch(`http://127.0.0.1:${port}/api/logs`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        level: 'special',
        message: 'Checkout completed',
        args: ['Checkout completed', { orderId: '123', amount: 49.99 }],
        starred: true,
        source: 'reverseLogger',
      }),
    });
    const specialData = await specialRes.json();
    assert(specialRes.status === 200, 'Special log creation should succeed');
    assert(specialData.log.starred === true, 'Special log should have starred=true');
    assert(specialData.log.source === 'reverseLogger', 'Special log source should be reverseLogger');

    // Query starred logs via GET /api/logs?starred=true
    const starredRes = await fetch(`http://127.0.0.1:${port}/api/logs?starred=true`);
    const starredData = await starredRes.json();
    assert(starredData.total === 1, `Expected 1 starred log, got ${starredData.total}`);
    assert(starredData.logs[0].message === 'Checkout completed', 'Starred log message mismatch');

    // Query starred logs via alias GET /api/logs/starred
    const aliasRes = await fetch(`http://127.0.0.1:${port}/api/logs/starred`);
    const aliasData = await aliasRes.json();
    assert(aliasData.total === 1, `Expected 1 starred log on /api/logs/starred, got ${aliasData.total}`);

    // Toggle star via POST /api/logs/:id/star
    const logId = specialData.log.id;
    const toggleRes = await fetch(`http://127.0.0.1:${port}/api/logs/${logId}/star`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ starred: false }),
    });
    const toggleData = await toggleRes.json();
    assert(toggleRes.status === 200, 'Star toggle should succeed');
    assert(toggleData.starred === false, 'Star state should be updated to false');

    const checkStarred = await fetch(`http://127.0.0.1:${port}/api/logs/starred`);
    const checkData = await checkStarred.json();
    assert(checkData.total === 0, 'Starred list should now be empty after unstarring');

    await server.close();
    console.log('   ✓ Starred Logs & Special Logs API OK');
  }

  // --- Test Suite 3: Web Dashboard Route (/logs) ---
  {
    console.log('3. Testing Web Dashboard Route (/logs)...');
    const dbPath = path.join(testDbDir, 'test3.db');
    if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);

    const port = 5103;
    const server = createServer({ port, dbPath });
    await server.listen(port);

    const dashRes = await fetch(`http://127.0.0.1:${port}/logs`);
    assert(dashRes.status === 200, 'GET /logs should return status 200');
    const contentType = dashRes.headers.get('content-type');
    assert(contentType !== null && contentType.includes('text/html'), 'GET /logs should serve text/html');
    const htmlText = await dashRes.text();
    assert(htmlText.includes('Reverse Logger Dashboard'), 'Dashboard HTML should contain header text');

    await server.close();
    console.log('   ✓ Web Dashboard Route OK');
  }

  // --- Test Suite 4: Token Authentication & Public Endpoints ---
  {
    console.log('4. Testing Token Authentication & Public Endpoints...');
    const dbPath = path.join(testDbDir, 'test4.db');
    if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);

    const port = 5104;
    const token = 'my_secret_token';
    const server = createServer({ port, token, dbPath });
    await server.listen(port);

    // Public /script/client.js and /logs
    const scriptRes = await fetch(`http://127.0.0.1:${port}/script/client.js`);
    assert(scriptRes.status === 200, 'GET /script/client.js should remain public');

    const dashRes = await fetch(`http://127.0.0.1:${port}/logs`);
    assert(dashRes.status === 200, 'GET /logs should remain public');

    // Protected API without token
    const unauthGet = await fetch(`http://127.0.0.1:${port}/api/logs`);
    assert(unauthGet.status === 401, 'Unauthenticated GET /api/logs should return 401');

    // Protected API with Bearer token
    const authGet = await fetch(`http://127.0.0.1:${port}/api/logs`, {
      headers: { Authorization: `Bearer ${token}` },
    });
    assert(authGet.status === 200, 'Authenticated GET /api/logs should return 200');

    await server.close();
    console.log('   ✓ Token Authentication & Public Endpoints OK');
  }

  // --- Test Suite 5: CORS Preflight & Headers ---
  {
    console.log('5. Testing CORS Preflight & Headers...');
    const dbPath = path.join(testDbDir, 'test5.db');
    if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);

    const port = 5105;
    const server = createServer({ port, dbPath });
    await server.listen(port);

    const optionsRes = await fetch(`http://127.0.0.1:${port}/api/logs`, {
      method: 'OPTIONS',
      headers: {
        Origin: 'http://my-web-app.com',
        'Access-Control-Request-Method': 'POST',
      },
    });

    assert(optionsRes.status === 200 || optionsRes.status === 204, 'CORS OPTIONS preflight should succeed');
    const allowOrigin = optionsRes.headers.get('access-control-allow-origin');
    assert(allowOrigin !== null, 'Access-Control-Allow-Origin header must be set');

    await server.close();
    console.log('   ✓ CORS Preflight & Headers OK');
  }

  // --- Test Suite 6: High-Volume Batch Log Ingestion (1,000 Logs) ---
  {
    console.log('6. Testing High-Volume Batch Log Ingestion (1,000 Logs)...');
    const dbPath = path.join(testDbDir, 'test6.db');
    if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);

    const port = 5106;
    const server = createServer({ port, maxLogs: 2000, dbPath });
    await server.listen(port);

    const logsBatch = Array.from({ length: 1000 }, (_, i) => ({
      timestamp: new Date().toISOString(),
      level: i % 10 === 0 ? 'error' : i % 5 === 0 ? 'warn' : 'log',
      message: `Batch log message #${i + 1}`,
      args: [`Batch log message #${i + 1}`, { index: i + 1 }],
      url: 'http://app.local/stress-test',
      sessionId: 'sess_stress_1000',
    }));

    const startTime = Date.now();
    const batchRes = await fetch(`http://127.0.0.1:${port}/api/logs`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ logs: logsBatch }),
    });

    const duration = Date.now() - startTime;
    assert(batchRes.status === 200, 'Batch POST /api/logs status should be 200');

    const batchData = await batchRes.json();
    assert(batchData.success === true, 'batchData.success should be true');
    assert(batchData.count === 1000, `Expected 1000 logs inserted, got ${batchData.count}`);

    const getRes = await fetch(`http://127.0.0.1:${port}/api/logs?limit=10`);
    const getData = await getRes.json();
    assert(getData.total === 1000, `Expected total stored count 1000, got ${getData.total}`);

    console.log(`   ✓ Ingested 1,000 logs in batch mode cleanly in ${duration}ms OK`);
    await server.close();
  }

  // Clean test databases
  try {
    fs.rmSync(testDbDir, { recursive: true, force: true });
  } catch {
    // ignore
  }

  console.log('\n🎉 ALL 6 EXPANDED TEST SUITES PASSED CLEANLY!\n');
}

runAllTests().catch((err) => {
  console.error('\n❌ Test execution failed:', err);
  process.exit(1);
});
